### PR TITLE
Add option to dekonize peptide into AA list

### PR DESCRIPTION
**Pull request by melihyilmaz**
Added option for `detokenize` to return peptide sequence as a list of amino acids rather than only in the string format. This was needed in the context of Casanovo for cases where multiple N-terminal modifications are predicted back to back (e.g. -17.027+42.011) and the downstream regex logic fails to differentiate these PTMs. Refer to below discussion for more details:
https://github.com/Noble-Lab/casanovo/pull/87#discussion_r1023220461

### CODE REVIEW

**Review by bittremieux — APPROVED** [review]

**Comment by melihyilmaz** [comment]
@wfondrie Should I add a unit test for `detokenize` or is failure due to something else?

**Comment by wfondrie** [comment]
The above previous errors were due to a failure to upload test coverage to CodeCov, which hopefully I've fixed now 🤞 

>Should I add a unit test for detokenize

The answer to this question is always yes 😉

**Comment by wfondrie** [comment]
Is there a good reason to every return a string? It seems like we should just make it always return a list. It seems easy enough for the user to join the string if they desire. 🤔 

I'd ok with the breaking change for now, since I think Casanovo is currently the only dependent. What do you think @melihyilmaz and @bittremieux?

**Comment by bittremieux** [comment]
I concur.

**Comment by melihyilmaz** [comment]
Makes sense we can only return a list, I added it as an option to avoid breaking things down.

**Pull request merged**
